### ISSUE TITLE
What is "Roku", "Roku2", "Roku3"?

### ISSUE THREAD

**Issue by EnTerr** [rokudev/docs#1]
https://github.com/rokudev/docs/blob/master/develop/guides/performance.md rather cavalierly says:

> - Roku: 20 MB
> - Roku2: 44-45 MB
> - Roku3: 60 MB

What would constitute Roku, Roku2, Roku3 for the purposes of that page? Please be specific - best to use model number ranges (like in https://forums.roku.com/viewtopic.php?f=34&t=86471&start=15#p536994 ), since there have been dozens of models so far. Of note, there have been 3 different "Roku 2" hardware platforms. Where would "new stick" fall in that, where would 5xxx RokuTV be, et al?

**Comment by dngroku** [comment]
Replaced vague model names with code names.
