### ISSUE TITLE
Dev.Portal: "Web Description" Rejects New Lines. Regression!

### ISSUE THREAD

**Issue by EnTerr** [rokudev/docs#10]
Steps to reproduce:

1. open "Channel Store info" for a channel ( https://developer.roku.com/developer-channels/channels/edit/descriptions/<9999> )
2. In the "Web Description" text area, insert a new line (hit Enter or copy&paste plain text with new lines)
3. Press Save button, rejoice a "Sorry | An error was encountered with the form. Please correct the highlighted fields." modal dialog, with the "Web Description" being highlighted.

How should it work: it should allow new lines. These are correctly converted later to <br/> in the web channel store.  There was a bug like this before and seems it "came back alive", hence regression.

**Comment by EnTerr** [comment]
See https://forums.roku.com/viewtopic.php?f=34&t=97125 for the original report on the current bug

**Comment by dannykng** [comment]
Web Description regression has been fixed as of 12/7/2016.
