### ISSUE TITLE
Create and Save in-Channel product doesn't work

### ISSUE THREAD

**Issue by dgpro** [rokudev/docs#11]
Hi,
I was trying to update one of my in-Channel products but when I click Save button nothing happens and there is a javascript error in the browser developer console. I've tried different browsers Chrome 54, Firefox 48, IE, Microsoft Edge but no avail. I even tried to delete the product and create a new one but Create button doesn't work either with the same console error:
[Screenshot](http://i.imgur.com/ewt2d5S.png?1)

**Comment by EnTerr** [comment]
Confirmed! Trying to create new product at https://developer.roku.com/products/create/digital , "Create" button "does nothing", the following crops out in console:

```diff
-&#x1F53B; global.js:3 Uncaught Unable to find the input element
rethrowCaughtError @ global.js:3
processEventQueue @ global.js:1
r @ global.js:3
handleTopLevel @ global.js:3
i @ global.js:3
a @ global.js:3
perform @ global.js:5
batchedUpdates @ global.js:3
a @ global.js:4
dispatchEvent @ global.js:3
```

**Comment by dgpro** [comment]
@jr-roku Could you please let me know when this major issue is sorted as it holds us up from testing and launching the app.

**Comment by jamesjordan** [comment]
Same here. Not able to test in-app billing. Very frustrating.

**Comment by jr-roku** [comment]
Sorry guys. A fix has just been published to the developer website. Please try again and LMK if there are still problems.

**Comment by dgpro** [comment]
@jr-roku Hi, thanks for an update.
There si another issue now, when I save/update existing product, after processing the page it shows me this message:

> There was an unexpected error in the website. The current page will not load. Close and re-open your browser, navigate back to the website, and try repeating your last actions. If the problem persists, please contact our support team.

It disappears when page is refreshed manually.

**Comment by jr-roku** [comment]
Thanks, we will look into it...

**Comment by marnusw** [comment]
I'm seeing the same problem. When trying to change the Product Name and saving the info I get the same error as @dgpro. When I refresh the page, the changes I made have not been applied because the POST to the server with those changes fail.

Please address this with high urgency. We are in the process of submitting our app for approval and these problems with the in-channel product pages make it impossible to use your site or get Roku apps working correctly.

**Comment by jr-roku** [comment]
@dgpro @marnusw We are not able to reproduce these issues. Can you contact me directly? jroberts AT roku.com

**Comment by jr-roku** [comment]
We are still investigating a problem whereby users see an error page after hitting the 'Submit' button when editing in-channel products. However, the changes are being saved so if you experience this problem, hit 'Refresh', you should see the changes have been applied.

If you want to change the name of an in-channel product, please make sure you expand the localization and set the name for all languages. If you only change the channel name then it has no effect.
