### ISSUE TITLE
[devTools] info page links to the wrong private channel for Stream Testing Tool 

### ISSUE THREAD

**Issue by EnTerr** [rokudev/docs#20]
https://github.com/rokudev/docs/tree/master/develop/developer-tools#stream-testing-tool
where it says 
>  _(**Note:** This tool requires a [companion Roku channel](https://my.roku.com/add/KX3UPK) to be installed on your device)_

that link has add-code KX3UPK, which is the wrong channel

**Comment by dannykng** [comment]
Thanks, incorrect channel code has been removed.

**Comment by EnTerr** [comment]
Radical idea - but how about adding **the correct code** instead of deleting the info that pvt channel is needed? ;-)

**Comment by dannykng** [comment]
The channel code is located in the Stream Testing Tool. If the channel code ever changes (ZJMQ6D5 is not a useful vanity code...), it will be updated there first.

**Comment by EnTerr** [comment]
The channel code is **hidden** in the STT. 
I am serious, it took me way too long to find it - it took another person's fresh eyes to go and click on the (?) icon - which to me seemed "obviously" placed there only to explain what an IP address is.

How about assigning it a useful, human readable vanity code and thus ensure it does not change between versions? ... and keep that code in the docs :)
