### ISSUE TITLE
[devPortal] should link to the "Developer Tools"

### ISSUE THREAD

**Issue by EnTerr** [rokudev/docs#21]
Somewhere in the [developer portal](https://developer.roku.com) there should be links to the ambitiously-named "Developer Tools" 3 web pages from http://devtools.web.roku.com/

See https://forums.roku.com/viewtopic.php?f=34&t=97827 for what i endured sleuthing for one of the "tools" - and if somebody who knows about their existence cannot find them - how are new developers supposed to discover them?

**Comment by dannykng** [comment]
Hi EnTerr,

Thanks for the feedback. As of now, there is a link under Developer Resources which points to: https://developer.roku.com/web/tools
