### ISSUE TITLE
can't publish to other store only US default

### ISSUE THREAD

**Issue by pm2i** [rokudev/docs#7]
Hi after the last change we are not able anymore to add channel to other store it's all the time US store on the Preferred Category

it seems  US is default, it is the only region that developers can publish to at the moment.

https://developer.roku.com/developer-channels/channels

thank you

**Comment by jr-roku** [comment]
Can you please send your email address and channel ID directly to email: jroberts AT roku.com

**Comment by EnTerr** [comment]
@jr-roku - this is not user# nor channel# related. Cue:
1. Go to Properties of any channel as any (normal/owner) user and 
2. try to change the Channel Stores (countries) in which channel is to be listed, then Save. 
3. Go back to Properties for said channel - your **changes are not saved**!

i just tried it with one of mine,
https://developer.roku.com/developer-channels/channels/edit/selectProperties/40442
and neither adding nor removing a country works.

Oh, and the drop-down menus totally don't work in Chrome on Windows (work in Chrome on Mac, IE on Windows) - but that's for another bug.

**Comment by siekermantechnology** [comment]
Yep, we encountered it as well and had contact with partner support to fix it for our specific channel, but it appears to be a general problem.

**Comment by EnTerr** [comment]
A better re-framing of the issue might be "unable to change country availability list" (which was set once when created or in the past, when the dev.portal was working)

**Comment by pm2i** [comment]
hi it's not only that if you want to submit a new private channel and you choose all the country for the store when you go to next page to upload the package only US  store will be shown on the preferred list and this is before you publish any package

**Comment by arabmate** [comment]
Hi, 

While submitting my new channels, i cant select multiple channel stores. Even after selecting all channel store, its only showing USA store only. Can anyone please help me to solve this issue? I had tried in firefox and chrome browsers to fix this issue but still the issue exist 

Thanks

**Comment by Arthy74** [comment]
Same issue here, this is quite critical i would say...

**Comment by arabmate** [comment]
So how long it might take to solve this issue?




On Wed, Oct 19, 2016 at 4:20 PM +0300, "Lionel ARNAUD" <notifications@github.com<mailto:notifications@github.com>> wrote:


Same issue here, this is quite critical i would say...

-

**Comment by jr-roku** [comment]
I'm apologize for the inconvenience. We have a fix under testing that should be pushed soon. If you have an urgent need to submit, please contact developer support or myself privately.

**Comment by jr-roku** [comment]
This issue is now fixed...
